### ISSUE TITLE
Create classpath file by automatically inferring dependencies from application's Maven build file

### ISSUE THREAD

**Issue by rachelt44** [konveyor/tackle-test-generator-cli#115]
**Is your feature request related to a problem? Please describe.**

Currently the user needs to manually specify all dependency jars for Tackle-test in a classpath file

**Describe the solution you'd like**

Given a maven build file for the application under test, automatically extract the list of dependency jars using the `mvn dependency:list` command, and create the classpath file

**Describe alternatives you've considered**

**Additional context**

**Comment by rmarting** [comment]
IMHO Maven is the most common building tool used in the Java ecosystem, so integrating tkltest with Maven will facilitate the use of the tool and reduce the manual steps to get the dependency list and so on. 

tkltest should be integrated firts with Maven before other building tools such as Gradle or Ant.

**Comment by rmarting** [comment]
Latest version in `main` branch is working successfully. This setup works for me:

```text
[generate]
    app_build_type = "maven"
    app_build_config_file = "/migration-sample-app/simple-sample-services/pom.xml"
```
