### ISSUE TITLE
tkltest requires to be executed from local source code path

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#117]
**Describe the bug**

After build locally the `tkltest` command following the instructions of the README.md file, you only are able to execute this command from the same path. If you move to a different folder, for example the application source code you want to test, and execute the command, then the command fails with an exception: 

```text
FileNotFoundError: [Errno 2] No such file or directory: 'lib/download/replacecall-4.2.6.jar'
```

Sample output:

```shell
❯ tkltest --verbose generate ctd-amplified
[tkltest|08:17:11.115] Loading config file tkltest_config.toml
Traceback (most recent call last):
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/venv/bin/tkltest", line 33, in <module>
    sys.exit(load_entry_point('tkltest', 'console_scripts', 'tkltest')())
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/tkltest.py", line 206, in main
    generate.process_generate_command(args, tkltest_config)
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/generate/generate.py", line 44, in process_generate_command
    dir_util.cd_output_dir(config['general']['app_name'])
  File "/home/rmarting/Workspaces/ws-konveyor/tackle-test-generator-cli/tkltest/util/dir_util.py", line 43, in cd_output_dir
    shutil.copy(os.path.join("lib", "download", "replacecall-4.2.6.jar"), os.path.join(output_dir, "lib", "download"))
  File "/usr/lib64/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'lib/download/replacecall-4.2.6.jar'
```

The tool should work indendently of the path where it was build, otherwise the user has to use the `--config-file` parameter to identify the path of the application to analyze, and the output folder always are located in the `tkltest` folder command. That behaviour is not more confortable if you want to analyze different applications and you have all the output folders in the same place.

**Attachments**

This issue happens always, it does not matter which configuration files or application you are testing.

**Environment information**

 - CLI version: Version 1.0.0 generated from main branch:
```shell
❯ tkltest -v
1.0.0
```

 - OS: Fedora 35
```shell
❯ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
❯ uname -a
Linux redhat 5.14.18-300.fc35.x86_64 #1 SMP Fri Nov 12 16:43:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots**

NA

**Additional context**

NA

**Comment by sinha108** [comment]
Fixed via PR https://github.com/konveyor/tackle-test-generator-cli/pull/266
