### ISSUE TITLE
Generate test cases for Maven multi-module applications

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#122]
**Is your feature request related to a problem? Please describe.**

Many JEE applications are defined as a set of different modules (Web, EJB, libs) using the [Maven Multiple Modules](https://maven.apache.org/guides/mini/guide-multiple-modules.html) feature. It is very tipical to have a JEE application defined as:

* application: Main folder to define the Maven multiple module structure:
* module-ejb: Subfolder with a Maven module to define the EJB application (jar file)
* module-web: Subfolder with a Maven module to define the Web application (war file)
* module-app: Subfoler with a Maven module to define the EAR application (ear file)

If you want to generate the test cases for the application, then you have to repeat for each module the sequence:

* Generate and define `toml` file
* Generate test cases for the module
* Execute test cases for the module

If the application has several modules, it is not practical to follow that approach and process.

**Describe the solution you'd like**

I would like to define the `toml` file once and describe the structure of the application following the Maven conventions, and delegate to 'tlktest' command to generate the test cases for every module with a single command and execution, and execute them as well.

**Describe alternatives you've considered**

Combining the `app_build_type = maven` property and Maven conventions will describe better the structure of the application and then `tkltest` analyze the source code and generate all the test cases following that structures. As user I want to describe few things and get the capabilities of the project.

Sample `toml` file:

```text
[general]
    app_name = "migration-sample-app"
    /* app_classpath_file generated from the pom.xml files */
    /* monolith_app_path generated from the pom.xml files */
    verbose = true

[generate]
    jee_support = true
    app_build_type = "maven"
    app_build_config_file = "pom.xml"
```

**Additional context**

A sample application with this structure is available [here](https://github.com/windup/migration-sample-app)

**Comment by rachelt44** [comment]
Implemented and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/194
