### ISSUE TITLE
Infer monolith app path from application's build file

### ISSUE THREAD

**Issue by Vicky-Goldin** [konveyor/tackle-test-generator-cli#137]
**Is your feature request related to a problem? Please describe.**

Currently, the user has to specify the monolith app class path in the configuration toml file.

**Describe the solution you'd like**

Given the application's build file (Ant or Maven or Gradle), automatically extract the list of monolith app class paths.

**Comment by rachelt44** [comment]
Support for the case of a Gradle build file implemented via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/160

**Comment by rachelt44** [comment]
Support for ant implemented via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/176

**Comment by rachelt44** [comment]
Support for maven implemented and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/169
