### ISSUE TITLE
obtain list of (modules + build files) from a list of module files - maven

### ISSUE THREAD

**Issue by haim-kermany** [konveyor/tackle-test-generator-cli#166]
we would like the user to supply a list of build files, we will get list of modules, and run on each module separately.

**Comment by rachelt44** [comment]
Implementation step for https://github.com/konveyor/tackle-test-generator-cli/issues/122

**Comment by rachelt44** [comment]
Done via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/173
