### ISSUE TITLE
Create toml file per module + build file

### ISSUE THREAD

**Issue by haim-kermany** [konveyor/tackle-test-generator-cli#168]
we would like the user to supply a list of build files, we will get list of modules, and run on each module separately.

the input is the user toml file and a build file of a specific module.
the output is a spcific toml file for the module.
we need to obtain module name, dev tests, and more

**Comment by rachelt44** [comment]
Implemented and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/182
