### ISSUE TITLE
Run generate/execute separately on each toml file on separate directory

### ISSUE THREAD

**Issue by haim-kermany** [konveyor/tackle-test-generator-cli#170]
we would like the user to supply a list of build files, we will get list of modules, and run on each module separately, on seperate directory.

**Comment by rachelt44** [comment]
Implementation step for https://github.com/konveyor/tackle-test-generator-cli/issues/122

**Comment by rachelt44** [comment]
Implemented and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/194
