### ISSUE TITLE
Enable merging reports of seperate modules

### ISSUE THREAD

**Issue by haim-kermany** [konveyor/tackle-test-generator-cli#171]
When the user supplies a list of build files, we will get list of modules, and run on each module separately (see issue https://github.com/konveyor/tackle-test-generator-cli/issues/122)

After running all modules, we would like to support an option to merge the coverage into one report, if requested by the user (see issue #108)

**Comment by rachelt44** [comment]
Implementation step for https://github.com/konveyor/tackle-test-generator-cli/issues/122

**Comment by rachelt44** [comment]
Implemented and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/207
