### ISSUE TITLE
Build Fail Error on Test Case execution

### ISSUE THREAD

**Issue by Nachiketh18** [konveyor/tackle-test-generator-cli#175]
**Describe the bug**

The Tackle tool throws the Build failed exception when we execute the testcase against  pdl common external service code (with enable of the user test case )

**Attachments**

tomal file 
[tkltest_config.txt](https://github.com/konveyor/tackle-test-generator-cli/files/7966366/tkltest_config.txt)
gradle error log
[gradle_error.txt](https://github.com/konveyor/tackle-test-generator-cli/files/7966370/gradle_error.txt)

**Environment information**

 - CLI version 1.3.0
 - OS: Windows

**Screenshots**

![issue](https://user-images.githubusercontent.com/25840917/151708297-fd0e3793-8f1d-4337-9f4d-265d921d71cc.JPG)

**Additional context**

If you need code please let us know

**Comment by rachelt44** [comment]
Fixes in dev-written tests build file supplied by the user fixed this issue

**Comment by haim-kermany** [comment]
the user had higher gradle version than the build.gradle file.
the solution was to downgrade the gradle version
