### ISSUE TITLE
Request to include submodules (or just test apps) in releases

### ISSUE THREAD

**Issue by w3dkramer** [konveyor/tackle-test-generator-cli#221]
**Is your feature request related to a problem? Please describe.**

Can some sub-modules be added to the release zip/tgz? My use case is testing my installation of the tackle-test ui cli with the petclinic app mentioned in the user guide. 
https://github.com/konveyor/tackle-test-generator-cli/tree/main/test/ui/data/webapps links to 
https://github.com/sinha108/tkltest-ui-webapps/tree/5fbc4c424eb77517dd5eeaa11a4b2fce8db67bf6 but is not included in the release.

**Describe the solution you'd like**

The simplest solution I see: Add sub-modules recursively in the checkout script. https://github.com/actions/checkout v3 has a 'submodlues' option that can be set to true to checkout recursively, and it supports SSH keys or PATs if needed.

**Describe alternatives you've considered**

I could see why you'd want to NOT include test apps for the sake of keeping the release size small or less complex! In that case, it would be very convenient if you could update the user guide for UI to include a link to https://github.com/sinha108/tkltest-ui-webapps as an instruction for users to download test apps themselves if they want to.

**Comment by sinha108** [comment]
We've added instructions for pulling the web apps using `git submodule` commands or getting them directly from the external repo. Including those apps in the releases or published docker images would make the artifacts bloated (we'll add more sample web apps in the future).
