### ISSUE TITLE
Failing to collect coverage for the evosuite tests for splitNjoin application

### ISSUE THREAD

**Issue by shailajapatel** [konveyor/tackle-test-generator-cli#222]
Executed the generate command for the existing splitNjoin application and see the following error -

`[tkltest|10:11:09.471] Failed to collect coverage for tests in the augmentation test pool, no tests are added.
`

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/88508562/158627854-5d05ff4c-a49e-4d00-a0a7-8ba7aefa1913.png">

**Environment information**

 - OS: macOS

**Comment by rachelt44** [comment]
@haim-kermany looks like in this case augmentation fails to collect code coverage both with online and with offline instrumentation, can you try to recreate and look into it?

**Comment by shailajapatel** [comment]
@rachelt44 - I'm using Gradle 7.4.1 version.

**Comment by rachelt44** [comment]
Fixed and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/233
