### ISSUE TITLE
Init command in toml file doesn’t create certain configuration options by default.

### ISSUE THREAD

**Issue by familrodrigues** [konveyor/tackle-test-generator-cli#225]
**Describe the bug**
Init command in toml file doesn’t create certain configuration options by default.
tkltest-unit config init --file tkltest_config.toml

**Environment information**

 CLI version - [tackle-test-generator-cli-v2.0.0-all-deps.zip](https://github.com/konveyor/tackle-test-generator-cli/releases/download/v2.0.0/tackle-test-generator-cli-v2.0.0-all-deps.zip)

 - OS: [Windows]
 - 
**Additional context**
Was following the quick start guide https://github.com/konveyor/tackle-test-generator-cli/blob/main/doc/unit/quick_start_guide.md
And could not find app_build_type in the generated toml file.
init command should be updated to include this by default.

**Comment by rachelt44** [comment]
Fixed and merged via PR: https://github.com/konveyor/tackle-test-generator-cli/pull/228
