### ISSUE TITLE
This is showing this error what is the reason? Can someone please explain.

### ISSUE THREAD

**Issue by AaravBaba** [konveyor/tackle-test-generator-cli#301]
![image](https://user-images.githubusercontent.com/85073024/186894021-27d0b194-0e82-4389-ab77-41c871a9ef46.png)

**Comment by rachelt44** [comment]
@AaravBaba can you please attach the `tkltest_config.toml` file you provided to the `generate ctd-amplified` command?

**Comment by AaravBaba** [comment]
> @AaravBaba can you please attach the `tkltest_config.toml` file you provided to the `generate ctd-amplified` command?
Here is my tkltest_config file
[tkltest_config.txt](https://github.com/konveyor/tackle-test-generator-cli/files/9433656/tkltest_config.txt)

**Comment by rachelt44** [comment]
@AaravBaba can you also attach `C:\\Users\\VVNT\\Desktop\\java projects\\addNum\\target\\classes\\classpath.txt`?

**Comment by AaravBaba** [comment]
> @AaravBaba can you also attach `C:\\Users\\VVNT\\Desktop\\java projects\\addNum\\target\\classes\\classpath.txt`?

[classpath.txt](https://github.com/konveyor/tackle-test-generator-cli/files/9433934/classpath.txt)

Ma'am this is simple maven application which add two number there were no specific app dependencies thats why i left this classpath.txt blank

**Comment by rachelt44** [comment]
@AaravBaba OK I see the problem, it is due to the space you have in `C:\\Users\\VVNT\\Desktop\\java projects\\addNum\\target\\classes`. We'll fix that. In the meantime as a workaround, you can rename the `java projects` folder name to a name that doesn't contain spaces.

**Comment by AaravBaba** [comment]
> @AaravBaba OK I see the problem, it is due to the space you have in `C:\\Users\\VVNT\\Desktop\\java projects\\addNum\\target\\classes`. We'll fix that. In the meantime as a workaround, you can rename the `java projects` folder name to a name that doesn't contain spaces.

Thanks for your valuable time ma'am i appreciate but its still showing this.
![image](https://user-images.githubusercontent.com/85073024/186950536-b76107cd-7b33-4106-80ec-7a088dd8b9c2.png)

And this is my simple project with output.
![image](https://user-images.githubusercontent.com/85073024/186950736-ab0d3d37-8523-4703-817a-63b9ca0a7060.png)


Again thanks for your time ma'am

**Comment by rachelt44** [comment]
@AaravBaba the JDK you provided is version 8, but from the error message we learn that the classes were compiled with java version 18. They should be compiled with java 8.

**Comment by AaravBaba** [comment]
> @AaravBaba the JDK you provided is version 8, but from the error message we learn that the classes were compiled with java version 18. They should be compiled with java 8.

Thank you so much ma'am this worked for me :)

![image](https://user-images.githubusercontent.com/85073024/187134483-0dde154d-b58b-47a6-a6dd-48840b7f9c62.png)

**Comment by rachelt44** [comment]
@AaravBaba glad to hear!
