### ISSUE TITLE
Testcases failing and skipping once running tkltest-ui command

### ISSUE THREAD

**Issue by henriquebafilho** [konveyor/tackle-test-generator-cli#305]
**Describe the bug**

Testcases are failing and skipping once I run the bellow command:
tkltest-ui --config-file ./test/ui/data/addressbook/tkltest_ui_config.toml --verbose execute

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

[crawl5.zip](https://github.com/konveyor/tackle-test-generator-cli/files/9567634/crawl5.zip)

**Environment information**

 - CLI version
 - OS: Windows

**Screenshots**

![Tackle Test issue](https://user-images.githubusercontent.com/17277553/190184463-66a74d50-9e77-489a-b307-fc6765709856.png)

**Additional context**

**Comment by henriquebafilho** [comment]
![image (1)](https://user-images.githubusercontent.com/17277553/192621408-2e58c4bf-b622-4e80-85fc-3905bf0ba8cd.png)

**Comment by rachelt44** [comment]
Documentation updated: https://github.com/konveyor/tackle-test-generator-cli/pull/319
