### ISSUE TITLE
Anyone can help with this error i tried to set path for java but still having issue.

### ISSUE THREAD

**Issue by AaravBaba** [konveyor/tackle-test-generator-cli#324]
Anyone can help with this error i tried to set path still having issue.

![image](https://user-images.githubusercontent.com/85073024/217150251-8306317a-c9cd-4706-aa36-03d352bf7610.png)
![image](https://user-images.githubusercontent.com/85073024/217150408-b5f45d3c-7b06-451e-bc4f-36137672dc42.png)

**Comment by rachelt44** [comment]
@AaravBaba I assume that you verified that the path `/home/vinay/java-1.8.0-openjdk-amd64/bin/java` does exist and is accessible from the terminal where you are running TackleTest?

**Comment by AaravBaba** [comment]
> @AaravBaba I assume that you verified that the path `/home/vinay/java-1.8.0-openjdk-amd64/bin/java` does exist and is accessible from the terminal where you are running TackleTest?

Hi rachel,
Thank you for reply, there were problem with my javajdk i resolved that and its working fine now 👍
