### ISSUE TITLE
Error while generating test in ctd-amplified mode

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#33]
Getting Error while generating tests using ctd-amplified mode, base test generator - combined
Command used: tkltest --config-file ./test/data/testapp/tkltest_config.toml --verbose generate ctd-amplified

Attaching Randoop_error_log when base test generator was set to randoop

 - CLI version - 0.0.1
 - OS: Windows 10

[testapp_CombinedTestGenerator_error.log](https://github.com/konveyor/tackle-test-generator-cli/files/6808287/testapp_CombinedTestGenerator_error.log)
[testapp.zip](https://github.com/konveyor/tackle-test-generator-cli/files/6808293/testapp.zip)
[testapp_CombinedTestGenerator_output.log](https://github.com/konveyor/tackle-test-generator-cli/files/6808335/testapp_CombinedTestGenerator_output.log)
[testapp_RandoopTestGenerator_error.log](https://github.com/konveyor/tackle-test-generator-cli/files/6808346/testapp_RandoopTestGenerator_error.log)

**Comment by rachelt44** [comment]
@nischay13may please try again after renaming the` Tackle Test Tool` folder to not include spaces.

**Comment by rachelt44** [comment]
resolve
