### ISSUE TITLE
I can't specify my classes I want to test

### ISSUE THREAD

**Issue by ngovanminh3232** [konveyor/tackle-test-generator-cli#333]
**Is your feature request related to a problem? Please describe.**
I just want to specify test one class. Can you support that?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rachelt44** [comment]
@ngovanminh3232 you can specify the fully qualified name of your class (without the .class suffix) in the `target_classes` parameter in your toml file, and then test cases will be generated only for that class.

**Comment by ngovanminh3232** [comment]
Ohh I see that but I can't use for file .java
You have solution?

**Comment by rachelt44** [comment]
@ngovanminh3232 unfortunately we support only classes, if your code is not in a class we cannot target it.

**Comment by ngovanminh3232** [comment]
Yepp Thank you.
