### ISSUE TITLE
Error generating testcases with evosuite

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#34]
Error generating testcases with evosuite
Command used: tkltest --config-file ./test/data/testapp/tkltest_config.toml --verbose generate evosuite

 - CLI version - 0.0.1
 - OS: Windows 10

![tkltest_evosuite_error_ss](https://user-images.githubusercontent.com/22675218/125440965-31812ec0-28bf-44f9-bee9-00a10148c5e4.jpg)
[testapp.zip](https://github.com/konveyor/tackle-test-generator-cli/files/6808330/testapp.zip)

**Comment by rachelt44** [comment]
Fixed in core repo - added double quotes to handle spaces in file system paths
