### ISSUE TITLE
Unable to generate the test case against the Ant build 

### ISSUE THREAD

**Issue by Nachiketh18** [konveyor/tackle-test-generator-cli#46]
**Describe the bug**

As prerequisite
<img width="945" alt="Tackle-tool" src="https://user-images.githubusercontent.com/25840917/126448871-1430ddb7-c2c4-4592-94a6-1156b94aaf8e.PNG">
[MDH_TSS_Log.txt](https://github.com/konveyor/tackle-test-generator-cli/files/6853568/MDH_TSS_Log.txt)
 ,Added all the dependency jar of the project and specified the path in classpath.txt and when i try to run its throwing the "tackle-test-generator-cli-main doesn't exist" error in the console.

Following are the attachments on the issue
1.Log file 
2.Screenshot of the error

**Environment information**

 - CLI version 0.0.1
 - OS: Windows

**Comment by rachelt44** [comment]
@Nachiketh18 does the user name folder contain spaces?

**Comment by Nachiketh18** [comment]
@rachelt44 no ,its "C:\Users\NachikethPY\Documents\*"

**Comment by rachelt44** [comment]
Resolved by adding back the removed jars.
