### ISSUE TITLE
Not able to load project specific files

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#47]
Configured my project inside the test-generator-cli folder and tried to generate test cases using the below command:
tkltest --config-file ./test/data/pdl/common-externalid-service/tkltest_config.toml --verbose generate randoop
I got error as "Command line is too long".

Then, I removed some of the jars which I thought was not required to be in classpath. After removing the jars, the command is running but I am getting the below error. I added some of the files which the cli flagged in the excluded_class parameter in toml file. But its asking to remove many files which are specific to the project and may require generating test cases and should not be [excluded.]

Could not load class java.main.com.ibm.external.exception.SO2OException: Unable to load class "java.main.com.ibm.external.exception.SO2OException" due to exception: java.lang.SecurityException: Prohibited package name: java.main.com.ibm.external.exception

**Attachments**
Have attached error screenshot , toml file and classpath file for reference
**Environment information**
- OS: Windows
- 
(![TKLERROR_PART_1](https://user-images.githubusercontent.com/22675218/126453611-e14aba69-6261-4559-a4c6-3ac3d06d7027.jpg)
![TKLERROR_PART_2](https://user-images.githubusercontent.com/22675218/126453638-0f879092-0658-44af-880c-9a11ed6610bd.jpg)
)
![TKLERROR_PART_5](https://user-images.githubusercontent.com/22675218/126453767-a62df1e4-5de4-4398-9c1a-fee477857e9e.jpg)
![TKLERROR_PART_3](https://user-images.githubusercontent.com/22675218/126453779-f5812c4f-0875-455c-945d-03a855d7e8e7.jpg)
![TKLERROR_PART_4](https://user-images.githubusercontent.com/22675218/126453793-80a848b1-34a1-4150-af6f-fef2b2533329.jpg)

[commonExternalIdClassPath.txt](https://github.com/konveyor/tackle-test-generator-cli/files/6853862/commonExternalIdClassPath.txt)
[toml.txt](https://github.com/konveyor/tackle-test-generator-cli/files/6853870/toml.txt)

**Comment by rachelt44** [comment]
@nischay13may The excluded class list is for application classes that should be excluded as coverage targets. Are these indeed application classes? Their names in the toml file you sent start with `java.main.com.ibm.external`, is this indeed the package prefix or the folder prefix? 

How did you determine the jars that are not needed? are the targeted application classes running without them? if it needs them then so will tackle during test generation.

**Comment by nischay13may** [comment]
@rachelt44 Yes, they are application classes. Our project is Gradle project and the folder structure looks like
![image](https://user-images.githubusercontent.com/22675218/126601468-b8e8037b-6c22-4b7a-af17-3293a34d7e10.png)

Also the build folder has the generated classes in the same folder structure.
![image](https://user-images.githubusercontent.com/22675218/126601589-825c2064-13b8-4ee4-b0a5-475fd7fd8dc0.png)

There was no specific logic behind removing the jars. But if I add all the jars in the classpath then I am getting "Command line is too long" error again.

**Comment by rachelt44** [comment]
Resolved by moving the dependent jars to a new location.
