### ISSUE TITLE
ConcurrentModificationException while generating Testcases

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#51]
**Describe the bug**

As discussed in our call
Getting ConcurrentModificationException while running the below command:
tkltest --config-file ./test/data/pdl/common-externalid-service/tkltest_config.toml --verbose generate ctd-amplified

**Attachments**

To help us diagnose the failure, please add these attachments to the issue, as appropriate:

![image](https://user-images.githubusercontent.com/22675218/126764242-afba1b19-316d-4628-b079-cf257d76aad3.png)

[toml.txt](https://github.com/konveyor/tackle-test-generator-cli/files/6867865/toml.txt)

**Environment information**

 - OS: Windows

**Screenshots**

**Additional context**

**Comment by rachelt44** [comment]
@nischay13may please attach also the output of the `java -version` command. Thanks!

**Comment by nischay13may** [comment]
@rachelt44 PFA
![image](https://user-images.githubusercontent.com/22675218/126953331-1b125d72-54e9-4d2f-977e-253e4a491ea9.png)

**Comment by rachelt44** [comment]
Issue fixed. Please rerun the` download_lib_jars.sh` script from the `lib` folder to obtain the up-to-date version of the tackle core jar.
