### ISSUE TITLE
Execution hangs after a period if time with ctd-amplified mode

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#57]
**Describe the bug**

Tried to generate test cases using the below command on pdl common-externalid-service

tkltest --config-file ./test/data/pdl/common-externalid-service/tkltest_config.toml --verbose generate ctd-amplified

The cmd execution starts but after a period of time the execution gets stuck and the test cases are also not generated.

**Attachments**

Have attached the output log.

**Environment information**

 - CLI version
 - OS: Windows

**Screenshots**

[common-externalid-service_CombinedTestGenerator_output.log](https://github.com/konveyor/tackle-test-generator-cli/files/6936330/common-externalid-service_CombinedTestGenerator_output.log)

**Comment by rachelt44** [comment]
Fixed as part of recent general enhancements to sequence parsing. The fix should be obtained using the `download_lib_jars.sh`  script.

**Comment by rachelt44** [comment]
Resolved by running on latest version of the code
