### ISSUE TITLE
Test Execution Completed but no tests present in ctd-amplified folder

### ISSUE THREAD

**Issue by nischay13may** [konveyor/tackle-test-generator-cli#65]
**Describe the bug**

Ran tkltest generate on pdl product-dataload-service. Execution got completed but no tests present in ctd-amplified folder.
Project access given in IBM Git

**Environment information**

 - CLI version
 - OS: Windows

**Screenshots**

![image](https://user-images.githubusercontent.com/22675218/130962314-a50d4813-fde6-4f51-982e-8758526214ed.png)
![image](https://user-images.githubusercontent.com/22675218/130962352-509eb8d0-4d7f-4909-9480-4346e44f6cba.png)

**Comment by rachelt44** [comment]
@nischay13may  can you please point me to the `LIBERTY/jars` jars appearing in the classpath file? I cannot find them in the repository.

**Comment by rachelt44** [comment]
Resolved
