### ISSUE TITLE
Failed to load class org.slf4j.impl.StaticLoggerBinder failure

### ISSUE THREAD

**Issue by shailajapatel** [konveyor/tackle-test-generator-cli#68]
When executing tkltest --config-file ./test/data/hubtx/tkltest_config.toml --verbose generate ctd-amplified command for the application, received the following error message -

![image](https://user-images.githubusercontent.com/88508562/131024740-9dbcb7e1-db56-41d2-825c-ae7d89fbd2d9.png)

Environment information

- CLI version
- OS: macOS

**Comment by shailajapatel** [comment]
Found the issue and resolved it. Not an issue with tackle.

**Comment by jmontleon** [comment]
@shailajapatel can you explain or point to how you fixed it? I am seeing the same thing with a different application.

**Comment by shailajapatel** [comment]
@jmontleon - The reason I was getting that error was because the dependency wasn't created right. After generating the correct dependencies, this error went away.
