### ISSUE TITLE
Add an option to reuse basic block files

### ISSUE THREAD

**Issue by rachelt44** [konveyor/tackle-test-generator-cli#76]
**Is your feature request related to a problem? Please describe.**

Generation of basic block files is the most time consuming part of the `generate ctd-amplified` command. In some cases it can take hours, which makes  repeated invocation of test generation costly.

**Describe the solution you'd like**

When the application code remains the same and we want to re-generate tests for some reason, we can reuse the  basic block output from previous invocations of the `generate ctd-amplified` command. This can be achieved by adding a boolean config option `-reuse-basic-block-output` and assuming the files with the expected names and location already exist.

**Describe alternatives you've considered**

**Additional context**

**Comment by sinha108** [comment]
@rachelt44: To keep the option name consistent with `--base-test-generator`, maybe call it `--reuse-base-tests`?

**Comment by rachelt44** [comment]
@sinha108 sounds good.
