### ISSUE TITLE
Publish tlktest-cli binaries or container images to be downloaded by users

### ISSUE THREAD

**Issue by rmarting** [konveyor/tackle-test-generator-cli#90]
**As a** user
**I need** to download the binaries or to pull a container image of Tackle Test Generator CLI
**So that** I am ready to use the application instead of to build locally to use it.

The current installation process of `tkltest` command requires a set of developer tools (e.g.: Java, Maven, Ant, ...), GitHub credentials, and other tools (e.g: `docker`) to build locally the tool using the source code provided in the GitHub repository. So the process is focused for users with developer skills or have those tools to have its own `tkltest` tool.

Publishing `tkltest` command as a set of binaries or artifacts to be downloaed and installed in the user environment will help the users to adopt the tool easily, instead of to build locally and follow complex instructions to build the tool.

**Assumptions:** 

* Build and publish `tkltest` versions will be done by a release process not by the user.
* User will not require especific tools or accounts to use the command.

**Acceptance Criteria:**

* Available a download artifact with the cli command (e.g.: tarball from the releases github repo) 
* Available a container image with cli command to pull and run locally using `docker` or `podman` (e.g: image published in a container image registry such as [Quay](https://quay.io/) or [DockerHub](https://hub.docker.com/))
* Available installation instructions to download and install locally without need to build the tool by my own

**Comment by sinha108** [comment]
Workflows for creating self-contained releases and publishing container images implemented
