### ISSUE TITLE
The Tool is failing to generate the test case when flag -ac -rbt provided

### ISSUE THREAD

**Issue by Nachiketh18** [konveyor/tackle-test-generator-cli#95]
As Documentation mentioned , When we execute the command with flag -ac -rbt the tool is throwing the error as mentioned in screenshot
 However without flag the tkltest is running as expected

**Command**
tkltest -cf ./test/data/pdl/common-externalid-service/tkltest_config.toml -vb generate ctd-amplified -ac -rbt

**Environment information**
 - CLI version
 - OS: Windows

![image](https://user-images.githubusercontent.com/25840917/136959495-90ccbca1-82e9-4dc0-8472-c91816065dbc.png)

**Comment by rachelt44** [comment]
@Nachiketh18 great thanks for the update
