### ISSUE TITLE
Create a junit file for each class as soon as the generation of its test sequences is completed

### ISSUE THREAD

**Issue by rachelt44** [konveyor/tackle-test-generator-cli#99]
**Is your feature request related to a problem? Please describe.**

Currently test files are written only at the end of the generation process, i.e., after test sequences were generated for all classes. If the extender process crashes for some reason, we are left with no junit tests.

**Describe the solution you'd like**

The extender should export test sequences as a junit file for each class upon completing its processing. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sinha108** [comment]
Implemented via issue https://github.com/konveyor/tackle-test-generator-core/issues/105
